#!
# Run this command to assign proper premissions to redis data folder 
# sudo chown -R 1001:1001 redis/
#-------------------------------------------------------------------
version: '3'
services:
  postgres:
    build: ./postgres/
    volumes:
      - postgres-food-delivery-volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
      - POSTGRES_DB=dev
    ports:
      - 5432:5432

  pgadmin:
    image: dpage/pgadmin4:4.18
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@linuxhint.com
      - PGADMIN_DEFAULT_PASSWORD=secret
      - PGADMIN_LISTEN_PORT=80
    ports:
      - "8080:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    links:
      - "postgres:pgsql-server"

volumes:
  postgres-food-delivery-volume:
  pgadmin-data:
