version: 2.1

orbs:
  heroku: circleci/heroku@1.0.1

jobs:
  build-test:
    docker:
      - image: circleci/node:14.0.0
    steps:
      - checkout
      - run: npm install
      - run: npm test

workflows:
  build-test:
    jobs:
      - build-test
      - heroku/deploy-via-git