version: 2.1

orbs:
  heroku: circleci/heroku@1.0.1

jobs:
  build-test:
    docker:
      # specify the version you desire here
      - image: circleci/node:14.0.0

    steps:
      - checkout
      - run: npm install
      - run: npm test

workflows:
  build-test:
    jobs:
      - build-test
  heroku_deploy:
    jobs:
      - heroku/deploy-via-git
